name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login (Action)
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t horatiuandrei/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true horatiuandrei/react-test npm test

      - run: docker build -t horatiuandrei/multi-client ./client
      - run: docker build -t horatiuandrei/multi-nginx ./nginx
      - run: docker build -t horatiuandrei/multi-server ./server
      - run: docker build -t horatiuandrei/multi-worker ./worker